// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nstvtjtbgofksvzyusqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zdHZ0anRiZ29ma3N2enl1c3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzY0NTQsImV4cCI6MjA2MjgxMjQ1NH0.Yb-G8zOz-BG5DSod-bpERwLv_wfVXDf0ElX-H3G7Pak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);